In [3]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler,StandardScaler
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [6]:
def hr_preprocessing(sl=False,le=False,npr=False,amh=False,tsc=False,wa=False,pl5=False,slr=False,dp=False,lower_d=False,d_1=1):
    df = pd.read_csv('../Data/HR.csv')
    #1、清洗数据
    df = df.dropna(subset=['satisfaction_level','last_evaluation'])
    df = df[df['satisfaction_level']<=1][df['salary']!='nme']
    #2、得到标注
    label = df['left']
    df = df.drop('left',axis=1)
    #3、特征选择
    #4、特征处理
    scaler_lst = [sl,le,npr,amh,tsc,wa,pl5]
    column_lst = ['satisfaction_level','last_evaluation','number_project',\
                  'average_monthly_hours','time_spend_company','Work_accident',\
                  'promotion_last_5years']
    for i in range(len(scaler_lst)):
        if not scaler_lst[i]:
            df[column_lst[i]]=MinMaxScaler().fit_transform(df[column_lst[i]].values.reshape(-1,1)).reshape(1,-1)[0]
        else:
            df[column_lst[i]]=StandardScaler().fit_transform(df[column_lst[i]].values.reshape(-1,1)).reshape(1,-1)[0]
    scaler_lst = [slr,dp]
    column_lst = ['salary','department']
    for i in range(len(scaler_lst)):
        if not scaler_lst[i]:
            if column_lst[i]=='salary':
                df[column_lst[i]]=[map_salary(s) for s in df['salary'].values]
            else:
                df[column_lst[i]]=LabelEncoder().fit_transform(df[column_lst[i]])
            df[column_lst[i]]=MinMaxScaler().fit_transform(df[column_lst[i]].values.reshape(-1,1)).reshape(1,-1)[0]
        else:
            df = pd.get_dummies(df,columns=[column_lst[i]])
    if lower_d:
        return PCA(n_components=ld_n).fit_transform(df.values),label
    return df,label
d = dict([('low',0),('medium',1),('high',2)])
def map_salary(s):
    return d.get(s,0)

In [8]:
df,label=hr_preprocessing()

In [13]:
df

,satisfaction_level,last_evaluation,number_project,average_monthly_hours,time_spend_company,Work_accident,promotion_last_5years,department,salary
0,0.318681,0.265625,0.0,0.285047,0.125,0.0,0.0,0.777778,0.0
1,0.780220,0.781250,0.6,0.775701,0.500,0.0,0.0,0.777778,0.5
2,0.021978,0.812500,1.0,0.822430,0.250,0.0,0.0,0.777778,0.5
3,0.692308,0.796875,0.6,0.593458,0.375,0.0,0.0,0.777778,0.0
4,0.307692,0.250000,0.0,0.294393,0.125,0.0,0.0,0.777778,0.0
...,...,...,...,...,...,...,...,...,...
14994,0.340659,0.328125,0.0,0.257009,0.125,0.0,0.0,0.888889,0.0
14995,0.307692,0.187500,0.0,0.299065,0.125,0.0,0.0,0.888889,0.0
14996,0.307692,0.265625,0.0,0.219626,0.125,0.0,0.0,0.888889,0.0
14997,0.021978,0.937500,0.8,0.859813,0.250,0.0,0.0,0.888889,0.0
14998,0.307692,0.250000,0.0,0.289720,0.125,0.0,0.0,0.888889,0.0

In [10]:
label

0        1
1        1
2        1
3        1
4        1
        ..
14994    1
14995    1
14996    1
14997    1
14998    1
Name: left, Length: 14999, dtype: int64